/** @type {import('next').NextConfig} */
const redirectRoutes = [
  { src: "/why-dental-sealants-is-a-healthy-choice", des: "/blog/why-dental-sealants-is-a-healthy-choice" },
  { src: "/when-does-a-root-canal-treatment-become-crucial", des: "/blog/when-does-a-root-canal-treatment-become-crucial" },
  { src: "/which-type-of-dentures-fits-you", des: "/blog/which-type-of-dentures-fits-you" },
  { src: "/your-guide-for-getting-dental-implants", des: "/blog/your-guide-for-getting-dental-implants" },
  { src: "/isthere-such-a-thing-as-dental-emergencies", des: "/blog/isthere-such-a-thing-as-dental-emergencies" },
  { src: "/tips-for-brushing-flossing", des: "/blog/tips-for-brushing-flossing" },
  { src: "/how-to-deal-with-dental-crown-complications", des: "/blog/how-to-deal-with-dental-crown-complications" },
  { src: "/porcelain-inlays-onlays-difference-benefits", des: "/blog/porcelain-inlays-onlays-difference-benefits" },
  { src: "/common-misconceptions-about-porcelain-veneers", des: "/blog/common-misconceptions-about-porcelain-veneers" },
  { src: "/professional-teeth-whitening-faq", des: "/blog/professional-teeth-whitening-faq" },
  { src: "/porcelain-fixed-bridges-why-how", des: "/blog/porcelain-fixed-bridges-why-how" },
  { src: "/what-should-you-know-about-composite-fillings", des: "/blog/what-should-you-know-about-composite-fillings" },
  { src: "/significance-of-dental-exams", des: "/blog/significance-of-dental-exams" },
  { src: "/what-are-the-different-types-of-teeth-cleaning", des: "/blog/what-are-the-different-types-of-teeth-cleaning" },
  { src: "/how-to-properly-brush-and-flos", des: "/blog/how-to-properly-brush-and-flos" },
  { src: "/what-is-cosmetic-dentistry", des: "/blog/what-is-cosmetic-dentistry" },
  { src: "/who-is-the-right-candidate-for-fixed-bridge-treatment", des: "/blog/who-is-the-right-candidate-for-fixed-bridge-treatment" },
  { src: "/what-is-root-canal-therapy", des: "/blog/what-is-root-canal-therapy" },
  { src: "/advantages-and-disadvantages-of-dental-sealant", des: "/blog/advantages-and-disadvantages-of-dental-sealant" },
  { src: "/how-do-dental-veneers-work", des: "/blog/how-do-dental-veneers-work" },
  { src: "/what-is-the-procedure-for-a-dental-implant", des: "/blog/what-is-the-procedure-for-a-dental-implant" },
  { src: "/how-eating-disorders-affect-oral-health", des: "/blog/how-eating-disorders-affect-oral-health" },
  { src: "/effects-of-hormones-on-female-dental-health", des: "/blog/effects-of-hormones-on-female-dental-health" },
  { src: "/aging-and-dental-health", des: "/blog/aging-and-dental-health" },
  { src: "/do-mouthwashes-work", des: "/blog/do-mouthwashes-work" },
  { src: "/dental-care-during-pregnancy", des: "/blog/dental-care-during-pregnancy" },
  { src: "/orthodontics-benefits-for-adults", des: "/blog/orthodontics-benefits-for-adults" },
  { src: "/how-dental-implants-work", des: "/blog/how-dental-implants-work" },
  { src: "/advantages-of-porcelain-inlays-and-onlays", des: "/blog/advantages-of-porcelain-inlays-and-onlays" },
  { src: "/teeth-cleaning-and-deep-cleaning", des: "/blog/teeth-cleaning-and-deep-cleaning" },
  { src: "/three-orthodontic-treatment-phases", des: "/blog/three-orthodontic-treatment-phases" },
  { src: "/do-you-need-porcelain-veneers", des: "/blog/do-you-need-porcelain-veneers" },
  { src: "/is-dental-insurance-worth-the-cost", des: "/blog/is-dental-insurance-worth-the-cost" },
  { src: "/advantages-of-cosmetic-dentistry", des: "/blog/advantages-of-cosmetic-dentistry" },
  { src: "/what-is-general-dentistry-and-who-is-a-general-dentist", des: "/blog/what-is-general-dentistry-and-who-is-a-general-dentist" },
  { src: "/benefits-of-porcelain-fixed-bridges", des: "/blog/benefits-of-porcelain-fixed-bridges" },
  { src: "/pediatric-dentistry-with-kids-and-adolescents", des: "/blog/pediatric-dentistry-with-kids-and-adolescents" },
  { src: "/difference-between-dentures-and-partial-dentures", des: "/blog/difference-between-dentures-and-partial-dentures" },
  { src: "/orthodontics-what-is-the-specialty-of-an-orthodontist", des: "/blog/orthodontics-what-is-the-specialty-of-an-orthodontist" },
  { src: "/dental-bone-grafting", des: "/blog/dental-bone-grafting" },
  { src: "/function-of-a-dental-laboratory", des: "/blog/function-of-a-dental-laboratory" },
  { src: "/my-restoration-options-for-missing-teeth", des: "/blog/my-restoration-options-for-missing-teeth" },
  { src: "/dental-bridges-vs-implants", des: "/blog/dental-bridges-vs-implants" },
  { src: "/surgical-dentistry-or-oral-surgery", des: "/blog/surgical-dentistry-or-oral-surgery" },
  { src: "/digital-x-rays-as-compared-to-legacy-x-rays", des: "/blog/digital-x-rays-as-compared-to-legacy-x-rays" },
  { src: "/preventing-tooth-decay", des: "/blog/preventing-tooth-decay" },
  { src: "/all-on-six-implants", des: "/blog/all-on-six-implants" },
  { src: "/surgical-dentistry-options", des: "/blog/surgical-dentistry-options" },
  { src: "/porcelain-inlays-onlays", des: "/blog/porcelain-inlays-onlays" },
  { src: "/overall-impact-of-periodontal-disease", des: "/blog/overall-impact-of-periodontal-disease" },
  { src: "/how-teeth-grinding-can-damage-dentures", des: "/blog/how-teeth-grinding-can-damage-dentures" },
  { src: "/your-dental-health-while-you-sleep", des: "/blog/your-dental-health-while-you-sleep" },
  { src: "/learn-more-about-full-mouth-reconstruction", des: "/blog/learn-more-about-full-mouth-reconstruction" },
  { src: "/how-dental-implants-are-changing-lives", des: "/blog/how-dental-implants-are-changing-lives" },
  { src: "/extracting-wisdom-teeth", des: "/blog/extracting-wisdom-teeth" },
  { src: "/invisalign-treatment-tips", des: "/blog/invisalign-treatment-tips" },
  { src: "/teeth-whitening-advantages", des: "/blog/teeth-whitening-advantages" },
  { src: "/what-causes-bad-breath", des: "/blog/what-causes-bad-breath" },
  { src: "/athletes-and-good-dental-health", des: "/blog/athletes-and-good-dental-health" },
  { src: "/what-happens-during-a-routine-dental-check-up", des: "/blog/what-happens-during-a-routine-dental-check-up" },
  { src: "/good-dental-health-begins-with-good-food-choices", des: "/blog/good-dental-health-begins-with-good-food-choices" },
  { src: "/understanding-oral-health-during-pregnancy", des: "/blog/understanding-oral-health-during-pregnancy" },
  { src: "/what-are-my-denture-alternatives", des: "/blog/what-are-my-denture-alternatives" },
  { src: "/dental-cleaning-for-kids", des: "/blog/dental-cleaning-for-kids" },
  { src: "/the-benefits-of-dental-veneers", des: "/blog/the-benefits-of-dental-veneers" },
  { src: "/advanced-dental-implant-techniques", des: "/blog/advanced-dental-implant-techniques" },
  { src: "/how-long-does-a-dental-crown-treatment-take", des: "/blog/how-long-does-a-dental-crown-treatment-take" },
  { src: "/importance-of-flossing-in-dental-hygiene", des: "/blog/importance-of-flossing-in-dental-hygiene" },
  { src: "/the-differences-between-inlays-and-onlays", des: "/blog/the-differences-between-inlays-and-onlays" },
  { src: "/sideeffects-of-periodontal-disease", des: "/blog/sideeffects-of-periodontal-disease" },
  { src: "/dental-surgery-and-dental-health", des: "/blog/dental-surgery-and-dental-health" },
  { src: "/how-to-use-dental-insurance-wisely", des: "/blog/how-to-use-dental-insurance-wisely" },
  { src: "/digital-x-rays-in-modern-dentistry", des: "/blog/digital-x-rays-in-modern-dentistry" },
  { src: "/childrens-adolescents-pediatric-dentistry", des: "/blog/childrens-adolescents-pediatric-dentistry" },
  { src: "/whatistmj", des: "/blog/whatistmj" },
  { src: "/periodontal-disease-and-how-it-effects-overall-health", des: "/blog/periodontal-disease-and-how-it-effects-overall-health" },
  { src: "/dental-fluoride-and-the-effects-on-oral-health", des: "/blog/dental-fluoride-and-the-effects-on-oral-health" },
  { src: "/coronavirus-and-dental-health", des: "/blog/coronavirus-and-dental-health" },
  { src: "/dental-crowns-for-children", des: "/blog/dental-crowns-for-children" },
  { src: "/pediatric-dentist-a-dentist-for-kids", des: "/blog/pediatric-dentist-a-dentist-for-kids" },
  { src: "/root-canal-therapy-and-what-it-means-to-you", des: "/blog/root-canal-therapy-and-what-it-means-to-you" },
  { src: "/diet-effects-on-oral-health", des: "/blog/diet-effects-on-oral-health" },
  { src: "/do-i-need-a-professional-teeth-deep-cleaning", des: "/blog/do-i-need-a-professional-teeth-deep-cleaning" },
  { src: "/dental-veneer-benefits-for-patients", des: "/blog/dental-veneer-benefits-for-patients" },
  { src: "/do-i-need-gum-grafting", des: "/blog/do-i-need-gum-grafting" },
  { src: "/pick-your-shade-with-professional-teeth-whitening", des: "/blog/pick-your-shade-with-professional-teeth-whitening" },
  { src: "/special-care-for-kids-teeth", des: "/blog/special-care-for-kids-teeth" },
  { src: "/how-to-experience-a-better-smile", des: "/blog/how-to-experience-a-better-smile" },
  { src: "/knowing-the-stages-of-periodontitis", des: "/blog/knowing-the-stages-of-periodontitis" },
  { src: "/end-of-the-year-dental-insurance-benefit-strategies", des: "/blog/end-of-the-year-dental-insurance-benefit-strategies" },
  { src: "/how-early-should-kids-visit-their-dentist", des: "/blog/how-early-should-kids-visit-their-dentist" },
  { src: "/what-is-involved-with-getting-dental-veneers", des: "/blog/what-is-involved-with-getting-dental-veneers" },
  { src: "/learn-more-about-dental-crowns", des: "/blog/learn-more-about-dental-crowns" },
  { src: "/full-mouth-reconstruction-options", des: "/blog/full-mouth-reconstruction-options" },
  { src: "/side-effects-of-periodontal-disease-and-its-impact-on-overall-health", des: "/blog/side-effects-of-periodontal-disease-and-its-impact-on-overall-health" },
  { src: "/what-you-should-know-about-dental-implant-after-care", des: "/blog/what-you-should-know-about-dental-implant-after-care" },
  { src: "/dental-bridge-vs-partial-denture-advantage-and-disadvantages", des: "/blog/dental-bridge-vs-partial-denture-advantage-and-disadvantages" },
  { src: "/dental-sealants-a-basic-overview", des: "/blog/dental-sealants-a-basic-overview" },
  { src: "/porcelain-fixed-bridges", des: "/blog/porcelain-fixed-bridges" },
  { src: "/dental-bridges-vs-dental-implants", des: "/blog/dental-bridges-vs-dental-implants" },
  { src: "/what-to-know-before-getting-dental-veneers", des: "/blog/what-to-know-before-getting-dental-veneers" },
  { src: "/restoration-options-for-missing-teeth", des: "/blog/restoration-options-for-missing-teeth" },
  { src: "/how-to-deal-with-a-chipped-tooth", des: "/blog/how-to-deal-with-a-chipped-tooth" },
  { src: "/pros-and-cons-of-dental-bridges", des: "/blog/pros-and-cons-of-dental-bridges" },
  { src: "/invisalign-vs-braces", des: "/blog/invisalign-vs-braces" },
  { src: "/learn-more-about-dental-crown-treatment", des: "/blog/learn-more-about-dental-crown-treatment" },
  { src: "/sedation-dentistry-explained", des: "/blog/sedation-dentistry-explained" },
  { src: "/tooth-whitening-in-home-vs-in-office", des: "/blog/tooth-whitening-in-home-vs-in-office" },
  { src: "/what-to-expect-from-a-dental-crown-procedure", des: "/blog/what-to-expect-from-a-dental-crown-procedure" },
  { src: "/the-importance-of-surgical-dentistry", des: "/blog/the-importance-of-surgical-dentistry" },
  { src: "/how-long-does-a-root-canal-take", des: "/blog/how-long-does-a-root-canal-take" },
  { src: "/dental-emergencies-and-what-should-be-done", des: "/blog/dental-emergencies-and-what-should-be-done" },
  { src: "/gum-diseases-and-their-side-effect-on-the-heart", des: "/blog/gum-diseases-and-their-side-effect-on-the-heart" },
  { src: "/learn-more-about-teeth-whitening-technologies", des: "/blog/learn-more-about-teeth-whitening-technologies" },
  { src: "/my-dental-implant-options", des: "/blog/my-dental-implant-options" },
  { src: "/gum-diseases-and-their-side-effects-on-overall-health", des: "/blog/gum-diseases-and-their-side-effects-on-overall-health" },


  { src: "/teeth-whitening", des: "/services/teeth-whitening" },
  { src: "/prophylaxis-teeth-cleaning", des: "/services/prophylaxis-teeth-cleaning"},
  { src: "/how-to-properly-brush-and-floss", des: "/services/how-to-properly-brush-and-floss" },
  { src: "/dental-exams-and-x-rays", des: "/services/dental-exams-and-x-rays" },
]

const nextConfig = {
  reactStrictMode: true,
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
  swcMinify: true,
  
  async redirects() {

    return redirectRoutes.map((route) => {
      return {
        source: route.src,
        destination: route.des,
        permanent: true,
      };
    });
  },
};


module.exports = nextConfig;
